# -*- coding: utf-8 -*-
{
    'name': 'myfab Simulation par quantités',
    'version': '1.2.0',
    'author': 'myfab',
    'license': 'Open-prod license',
    'summary': 'Simulation par quantités',
    'category': 'Advanced',
    'description': """Simulation par quantités.""",
    'website': 'https://www.myfab.fr/',
    'module_type': 'base',
    'images': [],
    'depends': [
        'my_fab',
        'product',
        'sale_purchase',
        'quotation',
    ],
    'data': [
        'classes/data_intializer/MFDataInitializerSimulationByQuantityTrigger.yml',
        'views/BaseMenus.xml',
        'views/simulation/MFSimulationByQuantityLine.xml',
        'views/simulation/MFSimulationByQuantity.xml',
        'views/simulation_config/MFSimulationConfigField.xml',
        'views/simulation_config/MFSimulationConfig.xml',
        'views/product.xml',
        'views/quotation_line.xml',
        'views/sale_order.xml',
        'views/sale_order_line.xml',
        'views/myfab_simulation_by_quantity_view.xml',
        'wizards/simulation_global_value/MFWizardSimulationGlobalValue.xml',
        'wizards/simulation_creation/MFWizardSimulationGenericCreation.xml',
        'wizards/product_info_creation/MFWizardSimulationProductInfoCreation.xml',
    ],
    'qweb': [],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
