# -*- coding: utf-8 -*-
{
    'name': 'myfab tools',
    'version': '1.0.0',
    'author': 'myfab',
    'license': 'Open-prod license',
    'summary': 'Initialisation de la boite à outils pour myfab',
    'category': 'Base',
    'description': """Initialise la boite à outils (tools) pour myfab.""",
    'website': 'https://www.myfab.fr/',
    'module_type': 'base',
    'images': [],
    'depends': [],
    'data': [],
    'qweb': [],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'not_show': True,
}
