# -*- coding: utf-8 -*-
{
    'name': 'myfab Dependencies',
    'version': '1.0.0',
    'author': 'myfab',
    'license': 'Open-prod license',
    'summary': 'Initialisation des dépendances myfab',
    'category': 'Base',
    'description': """Initialisation des dépendances de modules myfab""",
    'website': 'https://www.myfab.fr/',
    'module_type': 'base',
    'images': [],
    'depends': [
        'base_openprod',
        'base',
        'web_kanban',
        'web_calendar',
        'auth_crypt',
        'decimal_precision',
        'web_tip',
        'maintenance_contract',
        'web_tree_field_color',
        'web_diagram',
        'mail',
        'web_view_editor',
        'web_editor',
        'web_to_upper',
        'web_float_time_seconds',
        'web_expression_builder',
        'web_char_trim',
        'favorite',
        'document',
        'web_highstock',
        'base_import',
        'web_kanban_gauge',
        'binary_attachment',
        'report',
        'web_openprod',
        'purchase',
        'delivery_address',
        'web_data_base_name',
        'auth_signup',
        'compute_stored_fields',
        'calendar',
        'charge',
        'analytic',
        'l10n_fr',
        'account_openprod',
        'base_iban',
        'data_base_report',
        'data_account_report',
        'edi_openprod',
        'mass_editing',
        'stock_location',
        'excel_import',
        'web_export_view',
        'mrp',
        'account',
        'warning',
        'account_voucher',
        'base_printers',
        'printers',
        'printers_mrp',
        'printers_stock',
        'printers_res_partner',
        'printers_resource',
        'workflow_initialization',
        'jasper_server',
        'workflow_migration',
        'account_chart',
        'web_modify_view',
        'web_view_field_list',
        'base_setup',
        'partner_openprod',
        'product',
        'excel_report',
        'fetchmail',
        'base_action_rule',
        'workflow_reinitialisation',
        'enterprise_social_network',
        'resource',
        'export_security',
        'web_field_selector',
        'stock',
        'board',
        'translator',
        'function_fields_translation',
        'sale',
        'sale_purchase',
        'web_verify_mail',
        'base_vat',
        'web_charts',
        'web',
        'web_mail_autocomplete',
        'planning',
        'myfab_purchase',
        'myfab_production',
        'myfab_logistics',
    ],
    'data': [],
    'qweb': [],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'not_show': True,
}
